require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.3.1
  NewCops: enable

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false