services:
  db:
    image: postgres:latest
    container_name: ingreedy_db
    environment:
      POSTGRES_DB: ingreedy_dev
      POSTGRES_USER: ingreedy
      POSTGRES_PASSWORD: '1NGr33Dy'
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  db_admin:
    image: dpage/pgadmin4
    container_name: ingreedy_db_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: ingreedy@ingreedy.com
      PGADMIN_DEFAULT_PASSWORD: '1NGr33Dy'
    ports:
      - "8080:80"
    volumes:
      - pgadmindata:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmindata: