services:
  db:
    image: postgres:latest
    container_name: ingreedy_db
    environment:
      POSTGRES_DB: ingreedy_dev
      POSTGRES_USER: ingreedy
      POSTGRES_PASSWORD: '1NGr33Dy'
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: