default: &default
  adapter: postgresql
  host: 127.0.0.1
  username: ingreedy
  password: 1NGr33Dy
  pool: 5

development:
  <<: *default
  database: ingreedy_dev

test:
  <<: *default
  database: ingreedy_test

production:
  <<: *default
  database: ingreedy_prod