name: CI

on: [push, pull_request]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  PG_HOST: ${{ secrets.PG_HOST }}
  PG_USER: ${{ secrets.PG_USER }}
  PG_PASS: ${{ secrets.PG_PASS }}
  DB_NAME: ${{ secrets.DB_NAME }}

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.PG_USER }}
          POSTGRES_PASSWORD: ${{ secrets.PG_PASS }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Code checkout
      uses: actions/checkout@v4

    - name: Ruby setup
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.1

    - name: Bundle install
      run: |
        gem install bundler
        bundle install

    - name: Rubocop lint
      run: bundle exec rubocop

    - name: Reek analysis
      run: bundle exec reek

    - name: Bundler audit
      run: bundle exec bundler-audit check --update

    - name: Database setup
      run: |
        bin/rails db:create
        bin/rails db:migrate

    - name: Tests execution
      run: bundle exec rspec

    - name: Tests coverage report
      uses: joshmfrankel/simplecov-check-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    environment: production
    runs-on: ubuntu-latest
    needs: build
    concurrency: deploy-group

    steps:
      - name: Code checkout
        uses: actions/checkout@v4
    
      - name: Fly.io cli setup
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Fly.io deployment
        run: flyctl deploy --remote-only
