name: CI

on: [push, pull_request]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  PG_HOST: ${{ secrets.PG_HOST }}
  PG_USER: ${{ secrets.PG_USER }}
  PG_PASS: ${{ secrets.PG_PASS }}
  DB_NAME: ${{ secrets.DB_NAME }}

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.PG_USER }}
          POSTGRES_PASSWORD: ${{ secrets.PG_PASS }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.1

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Lint code with RuboCop
      run: bundle exec rubocop

    - name: Code analysis with Reek
      run: bundle exec reek

    - name: Check for vulnerabilities with Bundler Audit
      run: bundle exec bundler-audit check --update

    - name: Set up the database
      run: |
        bin/rails db:create
        bin/rails db:migrate

    - name: Run tests
      run: bundle exec rspec

  deploy:
    environment: production
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    needs: build
    concurrency: deploy-group

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Set up Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy code
        run: flyctl deploy --remote-only
